# conda environment description file
#
# Create a conda environment in which to run Jupyter Notebooks in this directory with:
#
#   $ conda env create -f environment.yaml
#   $ conda activate LObecca
#
# To add new packages to the environment,
# add them to the dependencies list below,
# then update the activated environment with:
#
#   (LObecca)$ conda env update -f environment.yaml

name: LObecca

channels:
  - conda-forge
  - defaults

dependencies:
  - arrow
  - bottleneck
  - cmocean
  - dask
  - python-dateutil
  - jupyterlab
  - matplotlib
  - netCDF4
  - nco
  - netcdf-fortran
  - gfortran
  - numpy
  - pandas
  - pip
  - python=3.11
  - pytz
  - scipy
  - xarray
  - ffmpeg
  - IPython
  - cartopy
  - scikit-learn
  - gsw
  - openpyxl
 # - sqlalchemy=1.4.49 needed to pip install this one
  # - erdappy - also needed to pip install
 
 # pip install --user --editable /data1/parker/LO/lo_tools/lo_tools
